Llm eval improvements
robusta-dev/holmesgpt pull request #214
Opened 2024-11-27 12:57 UTC by nherment

2024-11-27 13:27 UTC, nherment commented on tests/llm/utils/langfuse.py
> +
This is not used but I suggest we keep it until we make a ruling on braintrust

2024-12-01 09:14 UTC, moshemorad requested changes

2024-12-01 09:14 UTC, moshemorad commented on pyproject.toml
> +playwright = "1.48.0"
Why we pinned it?

2024-12-01 09:14 UTC, moshemorad commented on tests/llm/fixtures/test_ask_holmes/07_high_latency/helm/Dockerfile
Thinking here loud, do we really want to duplicate those and not use the ones from the kubernetes demo repo?

2024-12-02 06:52 UTC, nherment commented on pyproject.toml
> +playwright = "1.48.0"
There was some issue with the newly released playwright wheel. It's fixed now and that change was reverted.

2024-12-02 08:48 UTC, nherment commented on tests/llm/fixtures/test_ask_holmes/07_high_latency/helm/Dockerfile
I think we want to avoid replicating indeed. Ideally we have everything in one place though but there is usefulness to the k8s demo repo beyond Holmes.

2024-12-02 11:51 UTC, moshemorad commented on tests/llm/fixtures/test_ask_holmes/07_high_latency/helm/Dockerfile
So why aren't we just use them from the demo repo?

2024-12-03 05:55 UTC, nherment commented on tests/llm/fixtures/test_ask_holmes/07_high_latency/helm/Dockerfile
This one `07_high_latency` is modified and not exactly the same as the k8s demo: it does not actually require DB connection. Others like `21_job_fail_curl_no_svc_account` have been ported as is from promptfoo but in most cases where promptfoo was using the k8s demo code directly, the same k8s demo code is used.

2024-12-05 08:36 UTC, nherment commented
@moshemorad what chages are needed to greenlight this PR?

2024-12-05 13:32 UTC, nherment commented
The previous commit freezes playwright to 1.48.0 due to https://github.com/microsoft/playwright-python/issues/2679

2024-12-06 09:10 UTC, arikalon1 approved these changes

2024-12-06 09:19 UTC, merged